
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUTTON_DEVICE_ID,
		XPAR_BUTTON_BASEADDR,
		XPAR_BUTTON_INTERRUPT_PRESENT,
		XPAR_BUTTON_IS_DUAL
	},
	{
		XPAR_LED_DEVICE_ID,
		XPAR_LED_BASEADDR,
		XPAR_LED_INTERRUPT_PRESENT,
		XPAR_LED_IS_DUAL
	},
	{
		XPAR_SWITCH_DEVICE_ID,
		XPAR_SWITCH_BASEADDR,
		XPAR_SWITCH_INTERRUPT_PRESENT,
		XPAR_SWITCH_IS_DUAL
	}
};


